version: '2.1'

services:
  horse:
    build: Docker/Horse
    environment:
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_DATABASE: 'kanbana'
      DB_PORT: '5432'
      DB_HOST: 'postgres'
    links:
      - postgres
    privileged: true
    tty: true
    ports:
      - '9000:9000'
      - '64211:64211'    

  goose:
    build: Docker/Goose
    environment:
      GOOSE_DRIVER: 'postgres'
      GOOSE_DATABASE: 'kanbana'
      GOOSE_USER: 'postgres'
      GOOSE_HOST: 'postgres'
      GOOSE_PASSWORD: 'postgres'
      GOOSE_PORT: '5432'
    volumes:
      - ./Src/Migrations:/migrations
    links:
      - postgres
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
    volumes:
       - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    links:
      - postgres
    logging:
      driver: 'none'

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'kanbana'
      PGDATA: '/data/postgres'
    volumes:
       - pg-data:/data/postgres
    ports:
      - '5432:5432'

volumes:
  pg-data:
  pgadmin-data:    
